* Notes: Phonation and the Larynx
** Phonation - The making of sounds using the vocal folds
** Larynx - The "voice box," containing the vocal folds.
** Vocal Folds - known (incorrectly) as vocal chords.  They come together and vibrate, upon the passing through of air.
** Epiglottis - covers the trachea when swallowing, prevents you from breathing in food.
** Hyoid bone, a bone connected to no other bones but keeping together many other muscles.  U-shaped, as shown on the diagram.  Located in the very front of the throat.
*** FUN FACT: strangulation breaks the hyoid bone, which is how they tell forensically when someone has been strangled to death.
** Thyroid bone: shaped like a shield, influences the pitch, commonly known as the Adam's Apple.  Protrudes out your neck.
** Notes on the diagram (to be placed online, eventually.)
*** Pretty much everything is named there.
*** Space in the vocal folds is called the glottis.  It's literally just the space, honest.
*** Crico-arytenoids pull vocal folds apart to open them.
*** Moving vocal folds back together is done by the inter-arytenoids.
*** Crico-thyroid changes pitch.  It's located where you would expect.
*** Thyro-arytenoid, which lies right against the vocal folds.  This prevents excessive stress by limiting the amount of possible elongation.
** Notes for the Final
*** The Glottis
*** The Thyroid
*** Crico-arytenoid pulls apart
*** Inter-arytenoid is between.  Obviously.
*** Crico-Thyroid changes pitch
*** Thyro-arytenoid limits pitch to avoid breaking the vocal folds.
