* Section 1 
** Opening
*** The book opens with Scyld Shefing's funeral
    People mourn his death, because he was a great king.

    Scyld was a great king because he was good at leading in battle, he had
    sons (which allowed the lineage to continue,) and he came up from
    nothing.  He was obeyed, because he was feared (Machiavellian ideals
    long before Machiavelli.)  He was especially feared by his enemies, but
    by his followers as well.
    
    He treated his followers fairly and rewarded them for their work.  He
    distributed the treasure to the warriors after battles.

    Being good enough at battle to be feared saves him lives and helps
    establishing peace.  He used violence and war for the sake of peace.
    With peace in his land, his people could prosper.  Their needs would
    be met.
    
    _Scyld_ is the benchmark for a good king, and these qualities are what
    all other kings are compared to.

*** Hrothgar builds a hall
    This is a mead-hall, for drinking.  The men would come home, and they 
    would come to the hall and drink mead.  It was a place of eating, and
    drinking, partying, and where the unmarried male warriors slept.
    
    Hrothgar wanted his mead hall to be the biggest and best building, to
    let his men know that he thought they were the best.  Hrothgar was 
    proud, but not arrogant.  Pride is justifiable.  The Anglo-saxons were
    not huge fans of humility.

    The people have a good time until the attack of Grendel.  

*** Grendel attacks
    Grendel is a demon, evil for the sake of evil, and has great bloodlust. 
    A descendant of Cain, and he's angry that he wasn't invited.  He's been
    excluded, and laughed at, and kills 30 men (daily.)

    This has been going on for 12 years, but after the second night they 
    started moving away from the mead hall.  This made Grendel successful
    in destroying the community, but only at night and he could not touch
    the throne.

    A weirgild is a way of making reparations in the Anglo-Saxon way of 
    doing things.  This was common within a tribe, and it was a way of 
    making a reparation and stop the bloodshed.  In battle, this happened
    to go to the winning tribe.  They offer one to Grendel, who refuses
    the offer on account of his bloodlust.
    
    Hrothgar doesn't fight Grendel because it would be foolish and bad
    for his people.  *Despite his pride, he puts the sake of his people*
    *first.*

*** Enter Beowulf
    Beowulf, like Grendel, has the strength of 30 men.  He has a reputation,
    and comes to help.

    Beowulf helps Hrothgar for two reasons:
      - Credentials, to add to his reputation.  Glory.
	(Notably, the Anglo-Saxons didn't have an afterlife.  To live on, 
	 one must be remembered by the Scopes.)
      - Beowulf's father did something, and went to Hrothgar's kingdom.  
	Since Hrothgar paid Beowulf's father's Weirgild, Beowulf feels a 
	debt of honor.  Even though he doesn't technically owe Hrothgar a
	thing, he wants to help.

    The people of his clan read the omens and believe Beowulf will have fate
    on his side.  The omens are good.

    Beowulf knows it will be equal, and things are looking good.

*** Beowulf arrives
    Immediately Beowulf's group are dressed well and in warrior's clothing,
    but are open about it.  Beowulf has the "Head of a Hero" meaning he has
    charisma and presence.
    
    Beowulf wasn't always a part of his clan's best.  He started from
    nothing, much like Scyfling.  He was now going on a glorious quest of 
    honor.

** The First Battle
* Section 2
** After the Battle
*** Gifts for Beowulf
    Beowulf is given great gifts for a warrior, and is told he will be
    treated as a son.
    
    Beowulf shuts up Unferth by proving him completely wrong and being
    a badass (as is characteristic of Beowulf.)  He does this so much
    so that when he goes to fight Grendel's mother Unferth gives him
    his sword.  For Unferth to offer his sword to Beowulf was a very
    major act.

    The sword was useless to Beowulf, but he gave it back and thanked
    Unferth for it.

*** Tracking Grendel
    Beowulf and the Geats and the Danes, to ensure a dead Grendel,
    track his bloody footprints.  Beowulf wants glory, and the first
    Scop to speak of Beowulf starts telling his story in the Germanic
    Alliterative verse.
    
    Beowulf can now go home, except...
** Grendel's Mother
*** The Attack of Grendel's Mother
    Grendel's mother never had anything to do with them, but she is
    grieving for her son and she wants the Weirgild for her son.  She
    killed one warrior, which may have been all she would have taken.

    Hrothgar doesn't want to take a chance.  He summons Beowulf, and
    promises more treasure.
    
    Beowulf takes him up for two reasons:
      + More glory!
      + Beowulf also wants to avenge Hrothgar's men who have died.
    
    Beowulf in some sense sort of got things done.

*** Grendel's Home
    A cave underwater, with a large air pocket.  The water on the
    surface is dark, full of creatures, and looks as though it is on
    fire.  A deer running from a wolf will stop and face the wolf
    before going through that water.

    Beowulf fearlessly goes down.
*** The fight with Grendel's Mother
    See Battle Spreadsheet.
*** After the Battle
    The celebration is before the hall gets burned to the ground, and
    the scop indicates that Hrothgar's kingdom will fall from failed
    alliances.  It won't be Beowulf's fault.

    The Cyclical view of history is important to this form.
*** TODO Tuesday's Reading - to 2220
* Section 3
* Battle Spreadsheet

|-------------------------+----------------------------+------------------------------------------------------------------+----------|
| Aspect                  | Battle 1                   | Battle 2                                                         | Battle 3 |
|-------------------------+----------------------------+------------------------------------------------------------------+----------|
| Motive                  |                            | Always good.                                                     |          |
|                         |                            |                                                                  |          |
| Location                |                            | Underwater.                                                      |          |
|                         |                            |                                                                  |          |
| Fate                    |                            | Beowulf knows nothing about Fate at this point, but partway      |          |
|                         |                            | through the battle fate helps him find the giant sword.  In      |          |
|                         |                            | Ancient lore, giants were evil.  It took evil to fight evil,     |          |
|                         |                            | and her blood melted the sword.                                  |          |
|                         |                            |                                                                  |          |
|                         |                            |                                                                  |          |
| Circumstance            |                            | Beowulf had to swim for a day, and is fighting in her territory, |          |
|                         |                            | so his use of weapons makes sense.  It's fair then, that he      |          |
|                         |                            | uses weapons.                                                    |          |
|                         |                            |                                                                  |          |
| Difficulty              | Didn't even break a sweat  | Needed his armor to survive, and took a difficult journey to get |          |
|                         |                            | to the battle.  More difficult, and wouldn't have survived if    |          |
|                         |                            | he hadn't had his armor.                                         |          |
|                         |                            |                                                                  |          |
| Things taken            | Grendel's arm.             | Wants Grendel's head, takes Grendel's head.                      |          |
|                         |                            |                                                                  |          |
| Accomplishment of Goals | Killed Grendel, but didn't | Killed Grendel's mother, bringing closure.                       |          |
|                         | actually solve problem     |                                                                  |          |
|                         |                            |                                                                  |          |
| Consequence             | Grendel's Mother           | None.  The water become clear when Beowulf kills Grendel's       |          |
|                         |                            | mother.  There are no negative consequences.                     |          |
|-------------------------+----------------------------+------------------------------------------------------------------+----------|
